//
// Generated file, do not edit! Created by opp_msgtool 6.0 from QueuePacket.msg.
//

#ifndef __QUEUEPACKET_M_H
#define __QUEUEPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class QueuePacket;
/**
 * Class generated from <tt>QueuePacket.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet QueuePacket extends cPacket
 * {
 *     double arrivalTime; // Tempo di arrivo nel sistema
 * }
 * </pre>
 */
class QueuePacket : public ::omnetpp::cPacket
{
  protected:
    double arrivalTime = 0;

  private:
    void copy(const QueuePacket& other);

  protected:
    bool operator==(const QueuePacket&) = delete;

  public:
    QueuePacket(const char *name=nullptr, short kind=0);
    QueuePacket(const QueuePacket& other);
    virtual ~QueuePacket();
    QueuePacket& operator=(const QueuePacket& other);
    virtual QueuePacket *dup() const override {return new QueuePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getArrivalTime() const;
    virtual void setArrivalTime(double arrivalTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const QueuePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, QueuePacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline QueuePacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<QueuePacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __QUEUEPACKET_M_H

